apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-18vs
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0012-tenant/tkrw-pr712-0075-0012-app/devfile-sample-18vs@sha256:cd83b86baee2eb532cd825193b7d84ddfd400298c909c5d4e158a6e4e6e43c7e
        name: my-nodejs
        resources: {}
status: {}
